### ISSUE TITLE
ZeroNet ShutDown from command line

### ISSUE THREAD

**Issue by bitcoren** [zeronet-enhanced/ZeroNet#4]
Hello.
How can I shutdown ZeroNet from command line Linux?
```
./zeronet.py siteCmd 1HeLLoPVbqF3UEj8aWXErwTxrwkyjwGtZN serverShutdown
respond:
{'cmd': 'confirm', 'params': ['Shut down <b>ZeroNet client</b>?', 'Shut down'], 'id': 1}
What can I do with this?
```
Thanks...

**Comment by slrslr** [comment]
Not a solution to a described issue, but to kill the zeronet, maybe this line in ~/.bashrc will make available command "znkill" that will kill the ZN:
`alias znkill='for pid in $(pidof runtime/bin/python3 /home/ME/zeronet/core/start.py); do kill -9 $pid; done'`

or if you want bigger chance of clean quit, maybe disconnect network and then kill

obviously if possible, quit ZN from within ZeroHello, three dots next to logo, Shut down
