### ISSUE TITLE
127.0.0.1:43110 entered into browser address bar loads the old ZeroHello, not the new one that this fork requires.

### ISSUE THREAD

**Issue by styromaniac** [zeronet-enhanced/ZeroNet#9]

**Comment by vorticalbox** [comment]
The README  still links to the original fork,

follow instructions are for linux you'll need to tweak for different OS

firstdownload the zip 

https://github.com/zeronet-enhanced/ZeroNet/archive/refs/heads/massive-rework.zip

create a python environment

```
python3 -m venv venv && source ./venv/bin/activate
```
then install with pip

```pip install -r requirements.txt```

then you can start `./start.py`

**Comment by styromaniac** [comment]
You have to clear the browser cache to fix this issue.
